//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application description page..
        /// </summary>
        internal static string About_Description {
            get {
                return ResourceManager.GetString("About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippets that require administrator permissions are marked as &quot;admin-only&quot;..
        /// </summary>
        internal static string Admin_Only {
            get {
                return ResourceManager.GetString("Admin_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Graph Snippets sample for ASP.NET 4.6.
        /// </summary>
        internal static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Graph Snippets sample.
        /// </summary>
        internal static string App_Name_Short {
            get {
                return ResourceManager.GetString("App_Name_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the snippet you want to run..
        /// </summary>
        internal static string Choose_Snippet {
            get {
                return ResourceManager.GetString("Choose_Snippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &lt;a href=&quot;URL&quot;&gt;here&lt;/a&gt; to consent to the admin-only scopes..
        /// </summary>
        internal static string ConsentLink {
            get {
                return ResourceManager.GetString("ConsentLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Warning:&lt;/b&gt; This operation cannot be undone..
        /// </summary>
        internal static string Delete_Warning {
            get {
                return ResourceManager.GetString("Delete_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caller needs to authenticate..
        /// </summary>
        internal static string Error_AuthChallengeNeeded {
            get {
                return ResourceManager.GetString("Error_AuthChallengeNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        internal static string Error_Introduction {
            get {
                return ResourceManager.GetString("Error_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in {0}: {1} {2}.
        /// </summary>
        internal static string Error_Message {
            get {
                return ResourceManager.GetString("Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept a meeting.
        /// </summary>
        internal static string Event_AcceptMeeting {
            get {
                return ResourceManager.GetString("Event_AcceptMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a meeting for which you are not the organizer. Organizers cannot accept their own invitations..
        /// </summary>
        internal static string Event_CannotAcceptOwnMeeting {
            get {
                return ResourceManager.GetString("Event_CannotAcceptOwnMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an event.
        /// </summary>
        internal static string Event_CreateEvent {
            get {
                return ResourceManager.GetString("Event_CreateEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete an event.
        /// </summary>
        internal static string Event_DeleteEvent {
            get {
                return ResourceManager.GetString("Event_DeleteEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get an event.
        /// </summary>
        internal static string Event_GetEvent {
            get {
                return ResourceManager.GetString("Event_GetEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get my calendar view.
        /// </summary>
        internal static string Event_GetMyCalendarView {
            get {
                return ResourceManager.GetString("Event_GetMyCalendarView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get my events.
        /// </summary>
        internal static string Event_GetMyEvents {
            get {
                return ResourceManager.GetString("Event_GetMyEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update an event.
        /// </summary>
        internal static string Event_UpdateEvent {
            get {
                return ResourceManager.GetString("Event_UpdateEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions.
        /// </summary>
        internal static string Extensions {
            get {
                return ResourceManager.GetString("Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deleted.
        /// </summary>
        internal static string Extensions_deleted {
            get {
                return ResourceManager.GetString("Extensions_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Extensions.
        /// </summary>
        internal static string Extensions_OpenExtensions {
            get {
                return ResourceManager.GetString("Extensions_OpenExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add open extension to me.
        /// </summary>
        internal static string Extensions_Open_Add {
            get {
                return ResourceManager.GetString("Extensions_Open_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete open extension for me.
        /// </summary>
        internal static string Extensions_Open_Delete {
            get {
                return ResourceManager.GetString("Extensions_Open_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get open extensions for me.
        /// </summary>
        internal static string Extensions_Open_Get {
            get {
                return ResourceManager.GetString("Extensions_Open_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update open extension for me.
        /// </summary>
        internal static string Extensions_Open_Update {
            get {
                return ResourceManager.GetString("Extensions_Open_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updated.
        /// </summary>
        internal static string Extensions_updated {
            get {
                return ResourceManager.GetString("Extensions_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the file content..
        /// </summary>
        internal static string FileContent_New {
            get {
                return ResourceManager.GetString("FileContent_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the updated file content..
        /// </summary>
        internal static string FileContent_Updated {
            get {
                return ResourceManager.GetString("FileContent_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File and folder.
        /// </summary>
        internal static string File_And_Folder {
            get {
                return ResourceManager.GetString("File_And_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a file. This snippet only works with a file..
        /// </summary>
        internal static string File_ChooseFile {
            get {
                return ResourceManager.GetString("File_ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a .txt file. This snippet only works with a .txt file..
        /// </summary>
        internal static string File_ChooseTextFile {
            get {
                return ResourceManager.GetString("File_ChooseTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a file.
        /// </summary>
        internal static string File_CreateFile {
            get {
                return ResourceManager.GetString("File_CreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a folder.
        /// </summary>
        internal static string File_CreateFolder {
            get {
                return ResourceManager.GetString("File_CreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a file or folder.
        /// </summary>
        internal static string File_DeleteFileOrFolder {
            get {
                return ResourceManager.GetString("File_DeleteFileOrFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download a file.
        /// </summary>
        internal static string File_DownloadFile {
            get {
                return ResourceManager.GetString("File_DownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get file or folder metadata.
        /// </summary>
        internal static string File_GetFileOrFolderMetadata {
            get {
                return ResourceManager.GetString("File_GetFileOrFolderMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get my drive.
        /// </summary>
        internal static string File_GetMyDrive {
            get {
                return ResourceManager.GetString("File_GetMyDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get my files and folders.
        /// </summary>
        internal static string File_GetMyFilesAndFolders {
            get {
                return ResourceManager.GetString("File_GetMyFilesAndFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get items that are shared with me*.
        /// </summary>
        internal static string File_GetSharedWithMe {
            get {
                return ResourceManager.GetString("File_GetSharedWithMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get sharing link.
        /// </summary>
        internal static string File_GetSharingLink {
            get {
                return ResourceManager.GetString("File_GetSharingLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update file contents (.txt file only).
        /// </summary>
        internal static string File_UpdateFileContent {
            get {
                return ResourceManager.GetString("File_UpdateFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update file or folder metadata.
        /// </summary>
        internal static string File_UpdateFileOrFolderMetadata {
            get {
                return ResourceManager.GetString("File_UpdateFileOrFolderMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a large file.
        /// </summary>
        internal static string File_UploadLargeFile {
            get {
                return ResourceManager.GetString("File_UploadLargeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some text content..
        /// </summary>
        internal static string GenericText {
            get {
                return ResourceManager.GetString("GenericText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a group (admin-only)*.
        /// </summary>
        internal static string Group_CreateGroup {
            get {
                return ResourceManager.GetString("Group_CreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a group (admin-only)*.
        /// </summary>
        internal static string Group_DeleteGroup {
            get {
                return ResourceManager.GetString("Group_DeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a group (admin-only)*.
        /// </summary>
        internal static string Group_GetGroup {
            get {
                return ResourceManager.GetString("Group_GetGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get groups (admin-only)*.
        /// </summary>
        internal static string Group_GetGroups {
            get {
                return ResourceManager.GetString("Group_GetGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get group members (admin-only)*.
        /// </summary>
        internal static string Group_GetMembers {
            get {
                return ResourceManager.GetString("Group_GetMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get groups I&apos;m a direct member of (admin-only)*.
        /// </summary>
        internal static string Group_GetMyMemberOfGroups {
            get {
                return ResourceManager.GetString("Group_GetMyMemberOfGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get group owners (admin-only)*.
        /// </summary>
        internal static string Group_GetOwners {
            get {
                return ResourceManager.GetString("Group_GetOwners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Office 365 groups (admin-only)*.
        /// </summary>
        internal static string Group_GetUnifiedGroups {
            get {
                return ResourceManager.GetString("Group_GetUnifiedGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update a group (admin-only)*.
        /// </summary>
        internal static string Group_UpdateGroup {
            get {
                return ResourceManager.GetString("Group_UpdateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your office.
        /// </summary>
        internal static string Location_DisplayName {
            get {
                return ResourceManager.GetString("Location_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        internal static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a message.
        /// </summary>
        internal static string Mail_DeleteMessage {
            get {
                return ResourceManager.GetString("Mail_DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a message.
        /// </summary>
        internal static string Mail_GetMessage {
            get {
                return ResourceManager.GetString("Mail_GetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get my Inbox messages.
        /// </summary>
        internal static string Mail_GetMyInboxMessages {
            get {
                return ResourceManager.GetString("Mail_GetMyInboxMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get my Inbox messages with attachments.
        /// </summary>
        internal static string Mail_GetMyInboxMessagesThatHaveAttachments {
            get {
                return ResourceManager.GetString("Mail_GetMyInboxMessagesThatHaveAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get my messages.
        /// </summary>
        internal static string Mail_GetMyMessages {
            get {
                return ResourceManager.GetString("Mail_GetMyMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move a message.
        /// </summary>
        internal static string Mail_MoveMessage {
            get {
                return ResourceManager.GetString("Mail_MoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply to a message.
        /// </summary>
        internal static string Mail_ReplyToMessage {
            get {
                return ResourceManager.GetString("Mail_ReplyToMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send mail.
        /// </summary>
        internal static string Mail_SendMessage {
            get {
                return ResourceManager.GetString("Mail_SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send mail with attachment.
        /// </summary>
        internal static string Mail_SendMessageWithAttachment {
            get {
                return ResourceManager.GetString("Mail_SendMessageWithAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following operations require an ID. To enable them, run a query and then choose an item from the results..
        /// </summary>
        internal static string Needs_Id {
            get {
                return ResourceManager.GetString("Needs_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have consented to the admin-only scopes..
        /// </summary>
        internal static string NoConsentRequired {
            get {
                return ResourceManager.GetString("NoConsentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippets that aren&apos;t supported for personal accounts are marked with an asterisk (*)..
        /// </summary>
        internal static string No_MSA {
            get {
                return ResourceManager.GetString("No_MSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed, but no results were returned..
        /// </summary>
        internal static string No_Results {
            get {
                return ResourceManager.GetString("No_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed. This call doesn&apos;t return anything..
        /// </summary>
        internal static string No_Return_Data {
            get {
                return ResourceManager.GetString("No_Return_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First attachment&apos;s name.
        /// </summary>
        internal static string Prop_AttachmentName {
            get {
                return ResourceManager.GetString("Prop_AttachmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment count.
        /// </summary>
        internal static string Prop_AttachmentsCount {
            get {
                return ResourceManager.GetString("Prop_AttachmentsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First attachment&apos;s size.
        /// </summary>
        internal static string Prop_AttachmentSize {
            get {
                return ResourceManager.GetString("Prop_AttachmentSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First attachment&apos;s type.
        /// </summary>
        internal static string Prop_AttachmentType {
            get {
                return ResourceManager.GetString("Prop_AttachmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendees.
        /// </summary>
        internal static string Prop_Attendees {
            get {
                return ResourceManager.GetString("Prop_Attendees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        internal static string Prop_Body {
            get {
                return ResourceManager.GetString("Prop_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string Prop_BodyPreview {
            get {
                return ResourceManager.GetString("Prop_BodyPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child count.
        /// </summary>
        internal static string Prop_ChildCount {
            get {
                return ResourceManager.GetString("Prop_ChildCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Prop_Created {
            get {
                return ResourceManager.GetString("Prop_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Prop_Description {
            get {
                return ResourceManager.GetString("Prop_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download URL.
        /// </summary>
        internal static string Prop_DownloadUrl {
            get {
                return ResourceManager.GetString("Prop_DownloadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Prop_Email {
            get {
                return ResourceManager.GetString("Prop_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time.
        /// </summary>
        internal static string Prop_End {
            get {
                return ResourceManager.GetString("Prop_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string Prop_From {
            get {
                return ResourceManager.GetString("Prop_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string Prop_Id {
            get {
                return ResourceManager.GetString("Prop_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsDraft.
        /// </summary>
        internal static string Prop_IsDraft {
            get {
                return ResourceManager.GetString("Prop_IsDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member count.
        /// </summary>
        internal static string Prop_MemberCount {
            get {
                return ResourceManager.GetString("Prop_MemberCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Prop_Name {
            get {
                return ResourceManager.GetString("Prop_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pass@word1.
        /// </summary>
        internal static string Prop_Password {
            get {
                return ResourceManager.GetString("Prop_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota.
        /// </summary>
        internal static string Prop_Quota {
            get {
                return ResourceManager.GetString("Prop_Quota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        internal static string Prop_Received {
            get {
                return ResourceManager.GetString("Prop_Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response status.
        /// </summary>
        internal static string Prop_ResponseStatus {
            get {
                return ResourceManager.GetString("Prop_ResponseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        internal static string Prop_Start {
            get {
                return ResourceManager.GetString("Prop_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream length.
        /// </summary>
        internal static string Prop_StreamLength {
            get {
                return ResourceManager.GetString("Prop_StreamLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string Prop_Subject {
            get {
                return ResourceManager.GetString("Prop_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Prop_Type {
            get {
                return ResourceManager.GetString("Prop_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        internal static string Prop_Updated {
            get {
                return ResourceManager.GetString("Prop_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPN.
        /// </summary>
        internal static string Prop_Upn {
            get {
                return ResourceManager.GetString("Prop_Upn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string Prop_Url {
            get {
                return ResourceManager.GetString("Prop_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with Microsoft.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} snippets.
        /// </summary>
        internal static string Snippets {
            get {
                return ResourceManager.GetString("Snippets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated .
        /// </summary>
        internal static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose another user. This snippet doesn&apos;t support deleting the current user..
        /// </summary>
        internal static string User_ChooseAnotherUser {
            get {
                return ResourceManager.GetString("User_ChooseAnotherUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a user (admin-only)*.
        /// </summary>
        internal static string User_CreateUser {
            get {
                return ResourceManager.GetString("User_CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a user (admin-only)*.
        /// </summary>
        internal static string User_DeleteUser {
            get {
                return ResourceManager.GetString("User_DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a user&apos;s direct reports (admin-only)*.
        /// </summary>
        internal static string User_GetDirectReports {
            get {
                return ResourceManager.GetString("User_GetDirectReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get me.
        /// </summary>
        internal static string User_GetMe {
            get {
                return ResourceManager.GetString("User_GetMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get my manager*.
        /// </summary>
        internal static string User_GetMyManager {
            get {
                return ResourceManager.GetString("User_GetMyManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get my photo*.
        /// </summary>
        internal static string User_GetMyPhoto {
            get {
                return ResourceManager.GetString("User_GetMyPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a user.
        /// </summary>
        internal static string User_GetUser {
            get {
                return ResourceManager.GetString("User_GetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a user&apos;s photo*.
        /// </summary>
        internal static string User_GetUserPhoto {
            get {
                return ResourceManager.GetString("User_GetUserPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get users.
        /// </summary>
        internal static string User_GetUsers {
            get {
                return ResourceManager.GetString("User_GetUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update a user (admin-only)*.
        /// </summary>
        internal static string User_UpdateUser {
            get {
                return ResourceManager.GetString("User_UpdateUser", resourceCulture);
            }
        }
    }
}
